#!/usr/bin/env bash
# configures an ubuntu server
mappings=("127.0.0.2 localhost" "8.8.8.8 facebook.com")
hosts_file="/etc/hosts"

for mapping in "${mapping[@]}"; do
	echo "$mapping" >> "$hosts_file"
done
