#!/usr/bin/env bash
# Displays "TO infinity and beyond" with
# a sleep 2 between iteration.
# I am invincible!!! when receiving a SIGTERM signal

while true
do 
    echo "TO infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
