#!/usr/bin/env bash
# Dispays 'Best School' 10 times, on 9th iteration displys 'Best'

# Initialize counter
n=0
# Iterate loop
while [$n -lt 10 ]
do
    echo 'Best School'
    if [ $n -eq 8 ]
    then
	echo 'Hi'
    fi
    i=$((n+1))
done
