#!/usr/bin/env bash
# Dispays "Best School" 10 times, on 9th iteration displys "Hi"

n=0

while [$n -le 10 ]; do
    if [ $n -eq 9 ]; then
	echo "Best School"
	echo "Hi"
    else
	echo "Best School"
    fi

    n=$((i+1))
done
